import type { Metadata } from "next";
import { Red_Hat_Text, } from "next/font/google";
import "./globals.css";
import AuthProvider from "./component/SessionProvider";

const redHatText = Red_Hat_Text({
  variable: "--font-Red_Hat_Text",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Article Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} antialiased`}
      >
       <AuthProvider>
        {children}
        </AuthProvider> 
        
      </body>
    </html>
  );
}
